"""Recomecando do zero

Revision ID: 8e89bcead571
Revises: 
Create Date: 2025-12-01 00:59:20.970502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e89bcead571'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('pai', sa.String(), nullable=True),
    sa.Column('mae', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cpf'), 'clientes', ['cpf'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_index(op.f('ix_clientes_rg'), 'clientes', ['rg'], unique=True)
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_id'), 'funcionarios', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('custo', sa.Float(), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('fornecedor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.create_table('receitas_oftalmologicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('validade_em', sa.Date(), nullable=False),
    sa.Column('medico', sa.String(), nullable=True),
    sa.Column('crm', sa.String(), nullable=True),
    sa.Column('od_esf_long', sa.String(), nullable=False),
    sa.Column('od_cil_long', sa.String(), nullable=True),
    sa.Column('od_eixo_long', sa.String(), nullable=True),
    sa.Column('oe_esf_long', sa.String(), nullable=False),
    sa.Column('oe_cil_long', sa.String(), nullable=True),
    sa.Column('oe_eixo_long', sa.String(), nullable=True),
    sa.Column('od_esf_perto', sa.String(), nullable=True),
    sa.Column('oe_esf_perto', sa.String(), nullable=True),
    sa.Column('adicao', sa.String(), nullable=True),
    sa.Column('dnp_od', sa.String(), nullable=True),
    sa.Column('dnp_oe', sa.String(), nullable=True),
    sa.Column('altura_od', sa.String(), nullable=True),
    sa.Column('altura_oe', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receitas_oftalmologicas_cliente_id'), 'receitas_oftalmologicas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_receitas_oftalmologicas_id'), 'receitas_oftalmologicas', ['id'], unique=False)
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_os', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('tipo_lente', sa.Enum('SURFACADA', 'PRONTA', name='tipolente'), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ORCAMENTO', 'PRODUCAO', 'PRONTO', 'ENTREGUE', 'CANCELADO', name='statusos'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas_oftalmologicas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordens_servico_id'), 'ordens_servico', ['id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_numero_os'), 'ordens_servico', ['numero_os'], unique=True)
    op.create_table('itens_os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens_servico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_os_id'), 'itens_os', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_os_id'), table_name='itens_os')
    op.drop_table('itens_os')
    op.drop_index(op.f('ix_ordens_servico_numero_os'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_id'), table_name='ordens_servico')
    op.drop_table('ordens_servico')
    op.drop_index(op.f('ix_receitas_oftalmologicas_id'), table_name='receitas_oftalmologicas')
    op.drop_index(op.f('ix_receitas_oftalmologicas_cliente_id'), table_name='receitas_oftalmologicas')
    op.drop_table('receitas_oftalmologicas')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_funcionarios_id'), table_name='funcionarios')
    op.drop_table('funcionarios')
    op.drop_index(op.f('ix_clientes_rg'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
